### ISSUE TITLE
Looks Funny 😜 

### ISSUE THREAD

**Issue by ryan-theta** [joshhighet/transl8#25]
Consider reading [CSS For Dummies](https://hackernoon.com/cascading-style-sheets-css-for-dummies)

**Comment by ryan-theta** [comment]
![image](https://user-images.githubusercontent.com/69495849/235581900-81a6315e-ea9e-499f-bbb9-5ace18f9f82f.png)

**Comment by joshhighet** [comment]
![IMG_9656](https://user-images.githubusercontent.com/17993143/235582049-fe86fd3b-ef9c-4503-a410-c205d1b94238.jpeg)
